### ISSUE TITLE
Config filters: Allow to specify callable/closure signature

### ISSUE THREAD

**Issue by MartinMystikJonas** [efabrica-team/phpstan-latte#120]
```
parameters:
  latte:
    filters:
      formatdate: 'callable(string, string=): string' 
```
